# Data
dataset_name: chexpert
anonymous_dataset_path: /nas-ctm01/datasets/public/MEDICAL/chestxray-explanation-catalogues/original/chexpert
real_dataset_path: /nas-ctm01/datasets/public/MEDICAL/CheXpert-small
#real_dataset_splits_path: /nas-ctm01/homes/fpcampos/dev/diffusion/medfusion/data/mimic-cxr-2.0.0-split.csv

# Models
# path to the models which must have been trained previously
verification_model: models/verification_model.pth
retrieval_model: models/retrieval_model.pth

# Outputs
# these are a set of intermediate outputs between the different stages of the pipeline
lookup_table_output: outputs_chexpert/lookup_table.pth
nearest_images_output: outputs_chexpert/nearest_images.csv
verification_output: outputs_chexpert/verification_results.csv
filtered_dataset_output: outputs_chexpert/filtered_dataset
